'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ChannelSummary

    '''<summary>
    '''txtChannel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChannel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlSDHD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSDHD As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlChannelType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChannelType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCategory As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkSingleFPCforAllRegions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSingleFPCforAllRegions As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ddlGenre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGenre As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkGenericSynopsis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGenericSynopsis As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEpisodeNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEpisodeNo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkStarCast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkStarCast As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkGuestName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGuestName As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtProviderName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProviderName1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProviderContact1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProviderContact1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProviderMail1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProviderMail1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEscalationPoc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEscalationPoc1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEscalationPOCContact1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEscalationPOCContact1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProviderName2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProviderName2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProviderContact2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProviderContact2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProviderMail2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProviderMail2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEscalationPoc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEscalationPoc2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEscalationPOCContact2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEscalationPOCContact2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProviderName3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProviderName3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProviderMail3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProviderMail3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProviderContact3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProviderContact3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEscalationPoc3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEscalationPoc3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtEscalationPOCContact3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEscalationPOCContact3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkPressRelease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPressRelease As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEpiodicSynopsisProgLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEpiodicSynopsisProgLevel As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEPisodicSynopsisInBulkfForMultipleEpisodes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEPisodicSynopsisInBulkfForMultipleEpisodes As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEPisodicTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEPisodicTitle As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtFeed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFeed As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkGenericImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkGenericImage As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEpisodicImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEpisodicImage As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkSpecialPrograms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSpecialPrograms As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkImagesofSpecialPrograms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkImagesofSpecialPrograms As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkActive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkActive As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnSaveMe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveMe As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lbID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''sqlDS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDS As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlDSCatgeory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDSCatgeory As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlDSGenre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDSGenre As Global.System.Web.UI.WebControls.SqlDataSource
End Class
