'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ChannelRegionalMaster

    '''<summary>
    '''lbCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCompanyName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ACE_txtChannel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ACE_txtChannel As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''txtChannel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChannel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlLanguage1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLanguage1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RFVtxtRegionalName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVtxtRegionalName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtRegionalName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegionalName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkSynopsis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSynopsis As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtHiddenId1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHiddenId1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAddRegionalName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddRegionalName As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grdRegionalNames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdRegionalNames As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''SqlmstChannel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlmstChannel As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''SqlmstLanguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlmstLanguage As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlDSRegionalMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDSRegionalMaster As Global.System.Web.UI.WebControls.SqlDataSource
End Class
