'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ChannelOnairOffAir

    '''<summary>
    '''grdAirtelOnair control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAirtelOnair As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grdChannelOnAir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdChannelOnAir As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grdAnyTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdAnyTime As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''grdChannelOffAir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdChannelOffAir As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''sqlDSgrdAirtelOnAir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDSgrdAirtelOnAir As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlDSgrdChannelOnAir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDSgrdChannelOnAir As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlDSgrdAnytime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDSgrdAnytime As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''sqlDSgrdChannelOffAir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDSgrdChannelOffAir As Global.System.Web.UI.WebControls.SqlDataSource
End Class
