'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RegProgramMaster

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''updPanelRegProgramMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updPanelRegProgramMaster As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''ddlChannelName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlChannelName As Global.AjaxControlToolkit.ComboBox

    '''<summary>
    '''SqlDSChannel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDSChannel As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ddlRegionalProgram control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRegionalProgram As Global.AjaxControlToolkit.ComboBox

    '''<summary>
    '''SqlmstProgram control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlmstProgram As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''ddlLanguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLanguage As Global.AjaxControlToolkit.ComboBox

    '''<summary>
    '''SqlmstLanguage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlmstLanguage As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''txtRegionalName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegionalName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ExttxtRegionalName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExttxtRegionalName As Global.AjaxControlToolkit.TextBoxWatermarkExtender

    '''<summary>
    '''RFVtxtRegionalName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVtxtRegionalName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtEpisodeNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEpisodeNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRegionalDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegionalDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ExttxtRegionalDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExttxtRegionalDescription As Global.AjaxControlToolkit.TextBoxWatermarkExtender

    '''<summary>
    '''txtHiddenId1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHiddenId1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAddRegionalName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddRegionalName As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''grdRegionalNames control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grdRegionalNames As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''sqlDSRegionalMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sqlDSRegionalMaster As Global.System.Web.UI.WebControls.SqlDataSource
End Class
